version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - 80:80
      - 8125:8125
    networks:
      - grafana-net
    environment:
      - STATSD_INTERFACE=tcp

networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true
